### ISSUE TITLE
Reduce meeting overhead

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#17]
```[tasklist]
### Tasks
- [ ] Goal: Reduce current meeting overhead (55 hrs total per month) by 20%
- [ ] Produce template for monthly updates
```

**Comment by ianhabit-gsa** [comment]
Team conducted a [brief audit](https://docs.google.com/spreadsheets/d/10eReiUGLtbnl7MVYGjK0SzMlWsz0EgVlMN5FIbzxosM/edit#gid=0) of meeting overhead. Current estimations are at 55 total man hours spent per month prepping and running recurring meetings that use the same material.

We are in total death by powerpoint mode. We want to reassess and examine how we can combine materials, assets, etc to reduce overhead and team stress.

**Comment by atabing11** [comment]
Started draft template here: https://docs.google.com/presentation/d/1D9q5udpAXVTKI0gCW-Ak3KspHfLVMGexV6E4BREeaG4/edit#slide=id.g27164a68139_0_6

**Comment by atabing11** [comment]
Right now i just outlined two options for an outline but haven't created the slides yet - curious on thoughts on either of the directions or if there is another outline we should consider. The main thing I'm trying to balance is organizing our product-specific updates alongside the wider program/service level updates
