### ISSUE TITLE
May AB/CCB Meeting Deck

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#21]

**Comment by ianhabit-gsa** [comment]
@cassandrajHall you can use the "Link" icon in the task bar in this comment feature to insert the link to the active deck. Once everyone has contributed, please move this card to "In Review" by dragging it or using the right hand side bar where it says "Status" and change it to "In Review."

**Comment by cassandrajHall** [comment]
The FY24 2nd QTR AB meeting will be combined with the monthly May 2024 CCB meeting on May 15th. Agenda includes: CCB topics to include UX updates, survey integration, AB/CCB workshop, Product roadmap & Near-term releases. AB topics to include Program highlights, financial overview, FY26 Budget Forecast outlook, and tentative schedule for BWG meetings. Meeting will conclude with display of scheduled FDMS user training dates for remainder of May and beginning of June 2024. Link to slides: https://docs.google.com/presentation/d/1uyCpZUUwdbPR9sSvGNd9FzE9jjks9c0dgYxUFu_st6I/edit?usp=drive_link
