### ISSUE TITLE
FOIA Request related to Docket: EPA-HQ-OPP-2020-0120

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#57]
Request and draft response will be in [this folder](https://drive.google.com/drive/folders/1PX_Nv0flWQkybvXnEaggKWsVp1-WJ_EH?usp=drive_link).

FOIA request for information regarding,  "Seeking the list of email addresses of those that subscribed to docket EPA-HQ-OPP-2020-0120."  We believe the information resides on the [regulations.gov](http://regulations.gov/) website.

Please find details in the attached pdf file. 

Deadline to TTS Office of Operations: 6/13/2024
Deadline to the requester: 6/27/2024

LT: Micah 
SME: Virginia Huth (OROS)
TTS Office of Operations: Donny/Neichole

Regards,
Donny Kwan

-------

Details
Request ID : 2024-FOI-00756
Request Type : FOIA
Requested By : [Moeller, Perri](https://www.tsgconsulting.com/professional/perri-moeller/)
Requested Date : May 01, 2024
Primary User : Duane Fulton
Assignment Note : Hi Donny - I believe this request is related to Regulations.gov and as a result, belongs to TTS. Before I assigned it to you, I sent a clarification request. Originally, the requester just stated "information" and they clarified by stating "We are seeking the list of email addresses of those that subscribed to this docket. Thank you.

**Comment by cassandrajHall** [comment]
GSA Legal reviewing to determine if email addresses should be redacted.
