### ISSUE TITLE
BeInformed prototyping milestones

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#63]
https://docs.google.com/document/d/1q_mv6JgawwTODnbGL-b_UVNZxMRQ3V0BLom5sN8J1tI/edit
```[tasklist]
### Tasks
- [x] Develop draft milestones to share with team
- [x] Working session with team to refine and align
```

**Comment by gsawdshaw** [comment]
https://docs.google.com/document/d/1q_mv6JgawwTODnbGL-b_UVNZxMRQ3V0BLom5sN8J1tI/edit#heading=h.yz3a3231xa74
