### ISSUE TITLE
Docket Center Services Surge CLIN Mod

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#7]
Waiting on Joyce Barbour (OGP- keeper of all the files/invoices etc) - can't write this without the information from her

**Comment by atabing11** [comment]
If this isn't done by the time Allison leaves, Joyce will take care of this with @cassandrajHall

**Comment by atabing11** [comment]
Assigning to @cassandrajHall for awareness and to follow up with Joyce when needed

**Comment by cassandrajHall** [comment]
Sending reminder to Tobias for follow-up with OGP COR

**Comment by cassandrajHall** [comment]
[IGCE](https://docs.google.com/spreadsheets/d/1_I8KhLVLGUXQKjoY4VwG-wn1qLpbVYsmGafMf2Anc0A/edit?usp=drive_link)
[Statement of Need](https://docs.google.com/spreadsheets/d/1_I8KhLVLGUXQKjoY4VwG-wn1qLpbVYsmGafMf2Anc0A/edit?usp=drive_link)

Scheduled to meet with COR (Joyce Barbour) 8/13/24 3pm for review

**Comment by cassandrajHall** [comment]
COR (Joyce Barbour) showed status of contract and CLINs within their contract system. All CLINs for mandatory labor categories (PM & processing staff) and optional (surge PM & processing staff) are available for the contractor to charge hours against. COR advised that a modification is not required to add funding to an existing CLIN. I sent update to FedWriters PM (Christina Sabovich) and copied the COR. Closing issue.
