### ISSUE TITLE
2024 FDMS Training eBlasts

### ISSUE THREAD

**Issue by cassandrajHall** [GSA-TTS/OROS-eRulemaking#72]
[July 2024 eBlast Word.pdf](https://github.com/user-attachments/files/15825535/July.2024.eBlast.Word.pdf)

**Comment by cassandrajHall** [comment]
Mon, 6/17/24 - govDelivery issues with account/password. Awaiting account to unlock.

**Comment by cassandrajHall** [comment]
eBlast sent out 6/20/2024 3:39pm

**Comment by ianhabit-gsa** [comment]
I'm going to close this one, but for more specific tracking, let's just create a new card monthly.
