### ISSUE TITLE
Arnella Terrell (DHS) problem with docket center contract?

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#85]

**Comment by cassandrajHall** [comment]
Forwarded email to Docket Svcs PM (Christina Sabovich) for review and feedback. Awaiting g-chat or email follow-up.

**Comment by cassandrajHall** [comment]
In a email, Arnella Terrell (DHS Lead) referenced guidance to eRulemaking Docket Services that comments from all .mil and .gov email addresses should not be posted. Docket Services team responded with sample of State and local government ending in .gov submitted comments, which to them was valid to posts. Arnella followed up in a subsequent email, requesting verification on whether Docket Services team ever posted comments from federal employees. Christina Sabovich has now responded.
