### ISSUE TITLE
Public request about a tracking number for Regs.gov comment

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#87]
To Whom It May Concern:

 

We submitted a comment to the Patent and Trademark Office proposed rule: Setting and Adjusting Trademark Fees During Fiscal Year 2025 on May 28, 2024, which was assigned comment tracking number lwq-v6pb-9136.

 

We would like to know the status of the comment, as we still do not see it on [regulations.gov](http://regulations.gov/).  Who do I need to contact at the USPTO to determine its status?

 

Thank you,

 

Jason Blair

Partner

**Comment by cassandrajHall** [comment]
Request sent to FDMS Help Desk for action. Ticket Case #00037618 assigned.

**Comment by cassandrajHall** [comment]
Agile5 reviewed and dtected the error in the Comment Tracking Number (letter lowercase-L confused with the number 1). Comment was posted to Regulations.gov. Responding back to the customer and closing issue.
